version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - run:
          name: install dependecies
          command: npm install

      - run:
          name: Run unit test
          command: npm test
